### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by steelbrain** [AtomLinter/linter-ui-default#34]
```
Uncaught (in promise) TypeError: Cannot read property 'start' of undefined
    at Editor.updateMessages (/home/steel/.atom/packages/linter-ui-default/lib/editor.js:46:41)
    at /home/steel/.atom/packages/linter-ui-default/lib/main.js:57:16
    at /usr/share/atom/resources/app.asar/src/workspace.js:295:16
    at /usr/share/atom/resources/app.asar/src/workspace.js:360:18
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at PaneContainer.module.exports.PaneContainer.addedPaneItem (/usr/share/atom/resources/app.asar/src/pane-container.js:375:27)
    at /usr/share/atom/resources/app.asar/src/pane-container.js:359:28
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app.asar/src/pane.js:355:20)
    at Pane.module.exports.Pane.activateItem (/usr/share/atom/resources/app.asar/src/pane.js:326:14)
    at /usr/share/atom/resources/app.asar/src/workspace.js:506:18
    at process._tickCallback (node.js:368:9)
```

**Comment by steelbrain** [comment]
Looks like we're not handling messages with no ranges :\

**Comment by Arcanemagus** [comment]
Shouldn't linter itself be rejecting those?

**Comment by steelbrain** [comment]
They are valid messages, we shuold be showing them

**Comment by Arcanemagus** [comment]
Whoops, scrolled down and saw the range is optional.

**Comment by steelbrain** [comment]
Fixed by Fixed by https://github.com/AtomLinter/linter-ui-default/pull/40
