### ISSUE TITLE
Uncaught TypeError: Cannot read property 'destroy' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-ui-default#41]
[Enter steps to reproduce below:]

I have _no_ idea.... hit this when a lint got triggered.

**Atom Version**: 1.6.0-beta5
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/AtomLinter/linter-ui-default) package, v0.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'destroy' of undefined

```
At /C:/Users/Landon%20Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:105

TypeError: Cannot read property 'destroy' of undefined
    at Editor.updateMessages (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:79:34)
    at LinterUI.didCalculateMessages (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/main.js:89:30)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:27:16
    at Set.forEach (native)
    at UIRegistry.didCalculateMessages (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:26:20)
    at file:///C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/linter.coffee:40:11
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at MessageRegistry.update (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/message-registry.js:115:20)
    at later (C:\Users\Landon Abney\Documents\GitHub-release\linter\node_modules\sb-debounce\index.js:9:14)
```

### Commands

```
     -1:01.8.0 core:move-left (atom-text-editor.editor.is-focused)
  4x -1:01.2.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -1:00.2.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
  2x -0:57 core:save (atom-text-editor.editor.is-focused)
  2x -0:08.2.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:06.1.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:06.1.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:05.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:05.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:05.4.0 docblockr:parse-tab (atom-text-editor.editor.is-focused)
     -0:05.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:02.1.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "linter-htmlhint",
      "language-markdown"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-ui-default": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.22
autocomplete-python, v1.6.1
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-chef, v0.8.0
language-docker, v1.1.6
language-elixir, v0.11.1
language-fortran, v2.0.9
language-haml, v0.23.15
language-ini, v1.14.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.3
linter-alex, v2.0.0
linter-bootlint, v1.0.0
linter-coffeelint, v1.1.2
linter-csslint, v1.3.1
linter-docker, v0.1.2
linter-elixirc, v1.1.5
linter-erb, v1.0.2
linter-eslint, v6.0.0
linter-flake8, v1.11.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.1.0
linter-javac, v1.7.0
linter-js-yaml, v1.2.5
linter-jscs, v3.4.6
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pep8, v1.2.1
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.1.8
linter-phpcs, v1.3.0
linter-phpmd, v1.4.1
linter-pylint, v1.2.0
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.4
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-scss-lint, v2.5.1
linter-stylelint, v1.13.1
linter-tidy, v2.1.0
linter-tslint, v0.6.0
linter-ui-default, v0.0.2
mapfile-grammar, v0.1.0
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-selection, v4.3.1
pigments, v0.24.1
seti-syntax, v0.4.1
seti-ui, v0.8.1
svn, v0.0.9
tab-control, v0.6.9
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-ui-default/pull/40

**Comment by Arcanemagus** [comment]
Just got this thrown for me again, different stack trace though:

```
C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:189
TypeError: Cannot read property 'destroy' of undefined
    at DisplayMarkerLayer.module.exports.DisplayMarkerLayer.destroyMarker (C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\text-buffer\lib\display-marker-layer.js:189:34)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:366:37
    at Set.forEach (native)
    at MarkerLayer.module.exports.MarkerLayer.destroyMarker (C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\text-buffer\lib\marker-layer.js:365:34)
    at Marker.module.exports.Marker.destroy (C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\text-buffer\lib\marker.js:269:18)
    at Editor.apply (C:\Users\Landon Abney\Documents\GitHub-release\linter-ui-default\lib\editor\index.js:236:20)
    at Editors.update (C:\Users\Landon Abney\Documents\GitHub-release\linter-ui-default\lib\editors.js:93:30)
    at LinterUI.render (C:\Users\Landon Abney\Documents\GitHub-release\linter-ui-default\lib\main.js:93:20)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:29:16
    at Set.forEach (native)
    at UIRegistry.render (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:28:20)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/main.js:82:23
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.14.0-beta3\resources\app.asar\node_modules\event-kit\lib\emitter.js:129:28)
    at MessageRegistry.update (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/message-registry.js:130:20)
    at later (C:\Users\Landon Abney\Documents\GitHub-release\linter\node_modules\sb-debounce\index.js:9:14)
```

New issue or a resurface? I'm on the current `master` (18ffcae86e16a8c9f5ac13ed4e683e7f3bdeb978)

**Comment by steelbrain** [comment]
Betting on it being an Atom beta issue
