### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBufferRange' of undefined

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-ui-default#42]
Another intermittent issue with no steps to reproduce...

**Atom Version**: 1.6.0-beta5
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/AtomLinter/linter-ui-default) package, v0.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'getBufferRange' of undefined

```
At /C:/Users/Landon%20Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:142

TypeError: Cannot read property 'getBufferRange' of undefined
    at Editor.updateBubble (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:108:45)
    at Editor.handleBubble (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:97:12)
    at C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/editor.js:23:12
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextEditor.module.exports.TextEditor.cursorMoved (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor.js:1692:27)
    at Selection.module.exports.Selection.markerDidChange (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\selection.js:926:21)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\selection.js:41:24
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at TextEditorMarker.module.exports.TextEditorMarker.notifyObservers (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor-marker.js:264:27)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor-marker.js:65:26
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at Marker.module.exports.Marker.emitChangeEvent (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\text-buffer\lib\marker.js:396:20)
    at Marker.module.exports.Marker.update (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\text-buffer\lib\marker.js:342:12)
    at Marker.module.exports.Marker.setHeadPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\node_modules\text-buffer\lib\marker.js:135:19)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadBufferPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor-marker.js:175:32)
    at TextEditorMarker.module.exports.TextEditorMarker.setHeadScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor-marker.js:185:19)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\cursor.js:67:31
    at Cursor.module.exports.Cursor.changePosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\cursor.js:673:7)
    at Cursor.module.exports.Cursor.setScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\cursor.js:65:19)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor.js:1482:23
    at TextEditor.module.exports.TextEditor.moveCursors (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor.js:1686:9)
    at TextEditor.module.exports.TextEditor.setCursorScreenPosition (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor.js:1481:19)
    at TextEditorComponent.module.exports.TextEditorComponent.onMouseDown (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor-component.js:729:25)
    at HTMLDivElement.<anonymous> (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta5\resources\app.asar\src\text-editor-component.js:3:61)
```

### Commands

```
  3x -4:18.2.0 core:backspace (atom-text-editor.editor.is-focused)
  4x -4:10.4.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "linter-htmlhint",
      "language-markdown"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-ui-default": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
atom-beautify, v0.28.22
autocomplete-python, v1.6.1
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-chef, v0.8.0
language-docker, v1.1.6
language-elixir, v0.11.1
language-fortran, v2.0.9
language-haml, v0.23.15
language-ini, v1.14.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.3
linter-alex, v2.0.0
linter-bootlint, v1.0.0
linter-coffeelint, v1.1.2
linter-csslint, v1.3.1
linter-docker, v0.1.2
linter-elixirc, v1.1.5
linter-erb, v1.0.2
linter-eslint, v7.0.0
linter-flake8, v1.12.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.1.0
linter-javac, v1.7.0
linter-js-yaml, v1.2.5
linter-jscs, v3.4.6
linter-jshint, v2.0.2
linter-jsonlint, v1.1.6
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pep8, v1.2.1
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.1.8
linter-phpcs, v1.3.0
linter-phpmd, v1.4.1
linter-pylint, v1.2.0
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.4
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-scss-lint, v2.5.1
linter-stylelint, v1.13.1
linter-tidy, v2.1.0
linter-tslint, v0.7.0
linter-ui-default, v0.0.2
mapfile-grammar, v0.1.0
minimap, v4.19.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-selection, v4.3.1
pigments, v0.24.1
seti-syntax, v0.4.1
seti-ui, v0.8.1
svn, v0.0.9
tab-control, v0.6.9
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-ui-default/pull/40
