### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by Arcanemagus** [AtomLinter/linter-ui-default#48]
[Enter steps to reproduce below:]

1. Open Atom
2. Disable the `linter` package

**Atom Version**: 1.6.0-beta8
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [linter-ui-default](https://github.com/AtomLinter/linter-ui-default) package, v0.0.2

### Stack Trace

Uncaught Error: Emitter has been disposed

```
At C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta8\resources\app.asar\node_modules\event-kit\lib\emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta8\resources\app.asar\node_modules\event-kit\lib\emitter.js:77:15)
    at Buffers.onDidChangeline (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/buffers.js:105:25)
    at LinterUI.activate (C:/Users/Landon Abney/Documents/GitHub-release/linter-ui-default/lib/main.js:29:18)
    at UIRegistry.add (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/ui-registry.js:16:10)
    at Linter.addUI (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/main.js:106:21)
    at Object.consumeUI (C:/Users/Landon Abney/Documents/GitHub-release/linter/lib/index.js:32:21)
    at Provider.module.exports.Provider.provide (C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta8\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\Landon Abney\AppData\Local\atom\app-1.6.0-beta8\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:419:9)
    at process._tickCallback (node.js:348:13)
```

### Commands

```
     -0:18.2.0 timecop:view (ul.list-inline.tab-bar.inset-panel)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      ".bin",
      "fast-eslint",
      "linter-flow",
      "atom-typescript",
      "markdown-preview-plus",
      "git-control",
      "git-history",
      "linter-gjslint",
      "language-markdown",
      "linter-tidy",
      "language-chef",
      "linter-csslint",
      "linter-bootlint",
      "linter-scss-lint"
    ],
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  },
  "linter-ui-default": {}
}
```

### Installed Packages

```coffee
# User
atom-autocomplete-php, v0.18.7
autocomplete-python, v1.7.0
docblockr, v0.7.3
editorconfig, v1.2.4
file-watcher, v0.4.0
highlight-selected, v0.11.2
language-docker, v1.1.6
language-elixir, v0.12.3
language-haml, v0.23.15
language-ini, v1.14.0
language-powershell, v2.1.0
language-r, v0.4.0
language-reg, v0.0.0
linter, v1.11.3
linter-alex, v2.0.0
linter-coffeelint, v1.1.2
linter-docker, v0.1.2
linter-elixirc, v1.1.5
linter-erb, v1.0.2
linter-eslint, v7.1.1
linter-flake8, v1.13.0
linter-foodcritic, v0.5.2
linter-golinter, v1.2.0
linter-haml, v1.2.0
linter-htmlhint, v1.1.0
linter-javac, v1.8.1
linter-js-yaml, v1.2.5
linter-jscs, v3.4.8
linter-jshint, v2.0.3
linter-jsonlint, v1.2.1
linter-lintr, v1.0.4
linter-lua, v1.0.1
linter-markdown, v1.5.0
linter-pep8, v1.2.1
linter-perl, v0.7.2
linter-perlcritic, v0.3.3
linter-php, v1.2.0
linter-phpcs, v1.3.1
linter-phpmd, v1.4.1
linter-pylint, v1.2.0
linter-rails-best-practices, v0.2.2
linter-reek, v2.1.5
linter-rubocop, v0.4.7
linter-ruby, v1.2.2
linter-stylelint, v2.0.1
linter-tslint, v0.8.3
linter-ui-default, v0.0.2
mapfile-grammar, v0.1.0
minimap, v4.20.0
minimap-find-and-replace, v4.5.0
minimap-git-diff, v4.2.0
minimap-highlight-selected, v4.4.0
minimap-linter, v1.1.1
minimap-selection, v4.4.0
pigments, v0.24.5
seti-syntax, v0.4.1
seti-ui, v0.9.1
svn, v0.0.9
tab-control, v0.6.9
trailing-spaces, v0.3.2

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Oh, interesting, tuns out Atom does not call the service getter twice. Disabling and then reenabling triggers this

**Comment by Arcanemagus** [comment]
Ah, might have been re-enabling. Triggered this when doing a quick Disable/Enable testing something else and just assumed this was thrown on the Disable.

**Comment by steelbrain** [comment]
Fixed by https://github.com/AtomLinter/linter-ui-default/commit/03a7d0ef586c862fc8fa053bdfbdaf597ddcbe4e
